
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gofootqyotymlkrbxxmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvZm9vdHF5b3R5bWxrcmJ4eG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODk1ODgsImV4cCI6MjA2MTY2NTU4OH0.3qzhFrcuMrn5vdsrSgyRSkn4vj5ARCHKePnba-dL5vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
